[build]
  publish = "built-storybooks"
  command = "yarn bootstrap --core && yarn build-storybooks"
[build.environment]
  NODE_VERSION = "10"
  YARN_VERSION = "1.19.1"
  YARN_FLAGS = "--version"
  DOTENV_DISPLAY_WARNING = "none"
  STORYBOOK_EXAMPLE_APP ="true"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
